name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run spotless + assemble with full stacktrace
        run: ./gradlew --no-daemon --stacktrace --info spotlessCheck assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TachiyomiSY-${{ github.sha }}.apk
          path: app/build/outputs/apk/debug/*.apk
